name: "deploy"
description: "Creates Teia deployments"
author: "cesargdm"
inputs:
  namespace:
    description: Release branches names
    required: true
  bucket:
    description: Origin Bucket ARN
    required: true
  originAccessIdentity:
    description: S3 Origin Access Identity ID
    required: true
  domainName:
    description: Alias domain name
    required: true
  certificateId:
    description: Certificate ID
    required: true
runs:
  using: "node12"
  main: "dist/deploy/index.js"
