name: "prebuild"
description: "Gets Teia prebuild Outputs"
author: "cesargdm"
inputs:
  release-branches:
    description: Release branches names
    default: "['main']"
    required: false
  production-branch:
    description: Production branch name
    default: main
    required: false
outputs:
  app-version:
    description: "App version based on package.json or git commit hash"
  branch:
    description: "Current git branch."
runs:
  using: "node12"
  main: "dist/prebuild/index.js"
